version: "3.7"
services:

  envoy:
    image: envoyproxy/envoy:v1.12.2
    volumes:
      - ./envoy.yaml:/etc/envoy/envoy.yaml
    environment:
      loglevel: debug
    networks:
      - envoymesh
    ports:
      - "9901:9901"
      - "10000:10000"

  redis:
    image: redis
    networks:
      - envoymesh
    ports:
      - "6379:6379"

  ratelimit:
    image: envoyproxy/ratelimit:v1.4.0
    command: ratelimit
    networks:
      - envoymesh
    ports:
      - 8080:8080
      - 8081:8081
      - 6070:6070
    depends_on:
      - redis
    volumes:
      - ./ratelimit-data:/data
    environment:
      - USE_STATSD=false
      - LOG_LEVEL=debug
      - REDIS_SOCKET_TYPE=tcp
      - REDIS_URL=redis:6379
      - RUNTIME_ROOT=/data
      - RUNTIME_SUBDIRECTORY=ratelimit

networks:
  envoymesh: {}